### ISSUE TITLE
Must I download that LM model ?

### ISSUE THREAD

**Issue by StevenLOL** [robmsmt/KerasDeepSpeech#1]
Must I download that LM model ? 
How to build LM from scratch  ?

**Comment by spyamine** [comment]
here is q link how to do it 👍 

http://victor.chahuneau.fr/notes/2012/07/03/kenlm.html

**Comment by robmsmt** [comment]
Yes, it uses KenLM and that guide is the one that I used. I have included it in the instructions as a link. Thank you!
